In [3]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\user\appdata\roaming\python\python313\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from pandas) (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\appdata\roaming\python\python313\site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\appdata\roaming\python\python313\site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import numpy as np
import pandas as pd

In [12]:
dataset = pd.read_csv("ratings.csv", header = None)
transactions = []
for i in range(0, 9743):
    transactions.append([str(dataset.values[i,j]) for j in range(0,3)])

In [13]:
from apyori import apriori
rules = apriori(transactions = transactions, min_support = 0.003, min_confidence = 0.2, min_lift = 3, min_length = 2, max_length = 2)

In [14]:
results = list(rules)
results

[RelationRecord(items=frozenset({'5.0', '1'}), support=0.013342912860515243, ordered_statistics=[OrderedStatistic(items_base=frozenset({'1'}), items_add=frozenset({'5.0'}), confidence=0.5138339920948617, lift=3.052612551817218)]),
 RelationRecord(items=frozenset({'19', '1.0'}), support=0.006466180847788156, ordered_statistics=[OrderedStatistic(items_base=frozenset({'1.0'}), items_add=frozenset({'19'}), confidence=0.2202797202797203, lift=3.0143052172546554)]),
 RelationRecord(items=frozenset({'17', '4.5'}), support=0.003592322693215642, ordered_statistics=[OrderedStatistic(items_base=frozenset({'17'}), items_add=frozenset({'4.5'}), confidence=0.3153153153153153, lift=4.860944805565059)]),
 RelationRecord(items=frozenset({'19', '2.0'}), support=0.029559683875602996, ordered_statistics=[OrderedStatistic(items_base=frozenset({'19'}), items_add=frozenset({'2.0'}), confidence=0.4044943820224719, lift=4.378876404494382), OrderedStatistic(items_base=frozenset({'2.0'}), items_add=frozenset({'19'}), confidence=0.32, lift=4.378876404494382)]),
 RelationRecord(items=frozenset({'28', '2.5'}), support=0.01211125936569845, ordered_statistics=[OrderedStatistic(items_base=frozenset({'2.5'}), items_add=frozenset({'28'}), confidence=0.2964824120603015, lift=5.058893416293376), OrderedStatistic(items_base=frozenset({'28'}), items_add=frozenset({'2.5'}), confidence=0.20665499124343256, lift=5.058893416293375)]),
 RelationRecord(items=frozenset({'62', '4.5'}), support=0.010058503541003797, ordered_statistics=[OrderedStatistic(items_base=frozenset({'62'}), items_add=frozenset({'4.5'}), confidence=0.259946949602122, lift=4.007378370211194)]),
 RelationRecord(items=frozenset({'5.0', '43'}), support=0.007697834342604947, ordered_statistics=[OrderedStatistic(items_base=frozenset({'43'}), items_add=frozenset({'5.0'}), confidence=0.6465517241379309, lift=3.841069175777964)]),
 RelationRecord(items=frozenset({'59', '5.0'}), support=0.006671456430257621, ordered_statistics=[OrderedStatistic(items_base=frozenset({'59'}), items_add=frozenset({'5.0'}), confidence=0.6074766355140188, lift=3.608929792568954)])]

In [15]:
def inspect(results):
    lhs         = [tuple(result[2][0][0])[0] for result in results]
    rhs         = [tuple(result[2][0][1])[0] for result in results]
    supports    = [result[1] for result in results]
    return list(zip(lhs, rhs, supports))
resultsinDataFrame = pd.DataFrame(inspect(results), columns = ['Product 1', 'Product 2', 'Support'])

In [16]:
resultsinDataFrame

  Product 1 Product 2   Support
0         1       5.0  0.013343
1       1.0        19  0.006466
2        17       4.5  0.003592
3        19       2.0  0.029560
4       2.5        28  0.012111
5        62       4.5  0.010059
6        43       5.0  0.007698
7        59       5.0  0.006671

In [17]:
resultsinDataFrame.nlargest(n = 10, columns = 'Support')

  Product 1 Product 2   Support
3        19       2.0  0.029560
0         1       5.0  0.013343
4       2.5        28  0.012111
5        62       4.5  0.010059
6        43       5.0  0.007698
7        59       5.0  0.006671
1       1.0        19  0.006466
2        17       4.5  0.003592